openapi: 3.0.3
info:
  title: Binar Bank Challenge Chapter 4 API Documentation
  description: >-
    This is a part of Binar JavaScript Backend Bootcamp - FGA Batch 2 Challenge Chapter 4. 

    The challenge is to build a _simple_ Bank System REST API where can handle basic CRUD (Create, Read, Update, dan Delete) operations.


    The REST API for now only supported on your localhost server, please provide and define your .env file.


    **Documentation will update accordingly**.


    Below are the detailed information on how to use the API, including all endpoints to use, request methods, and example responses.




    Some useful link(s):

    - [Binar BE Challenge CH4 Repository](https://github.com/jhontriboyke/binar-be-challenge-ch4)
  contact:
    email: jhontriboyke@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:PORT/api/v1
tags:
  - name: user
    description: User endpoints
  - name: account
    description: Account endpoints
  - name: transaction
    description: Transaction endpoints
paths:
  $ref: "./paths/index.yaml"
components:
  $ref: "./components/index.yaml"
